apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/caravaninteractive/servicebus-agenda-service:{{.VERSION}}"
  artifacts:
  - imageName: servicebus-agenda-service
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/caravaninteractive/servicebus-agenda-service:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: servicebus-agenda-service
        chartPath: charts/servicebus-agenda-service
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/caravaninteractive/servicebus-agenda-service"
          image.tag: "{{.TAG}}"
